# SPDX-License-Identifier: Apache-2.0

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-controller-plugin
  namespace: kubesan-system

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-controller-plugin
  namespace: kubesan-system
spec:
  selector:
    matchLabels: &labels
      kubesan.gitlab.io/component: csi-controller-plugin
  template:
    metadata:
      labels: *labels
      annotations:
        kubectl.kubernetes.io/default-container: csi-plugin
    spec:
      serviceAccountName: csi-controller-plugin
      containers:
        - name: csi-plugin
          image: kubesan # config.go expects this image in containers[0]
          args:
            - csi-controller-plugin
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: socket-dir
              mountPath: /run/csi
            - name: dev
              mountPath: /dev
          # TODO(user): Configure the resources accordingly based on the project requirements.
          # More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
        - name: csi-provisioner
          image: registry.k8s.io/sig-storage/csi-provisioner:v3.5.0
          args:
            - --extra-create-metadata  # to get PVC/PV info in CreateVolume()
          volumeMounts:
            - name: socket-dir
              mountPath: /run/csi
          # TODO(user): Configure the resources accordingly based on the project requirements.
          # More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
        - name: csi-snapshotter
          image: registry.k8s.io/sig-storage/csi-snapshotter:v6.3.3
          args:
            - --extra-create-metadata  # to get VS/VSC info in CreateSnapshot()
          volumeMounts:
            - name: socket-dir
              mountPath: /run/csi
          # TODO(user): Configure the resources accordingly based on the project requirements.
          # More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
      volumes:
        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/kubesan-controller
            type: DirectoryOrCreate
        - name: dev
          hostPath:
            path: /dev
            type: Directory
