# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-controller-plugin
  namespace: subprovisioner

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-controller-plugin
  namespace: subprovisioner
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels: &labels
      subprovisioner.gitlab.io/component: csi-controller-plugin
  template:
    metadata:
      labels: *labels
    spec:
      serviceAccountName: csi-controller-plugin
      hostPID: true
      containers:
        - name: csi-plugin
          image: &image quay.io/subprovisioner/subprovisioner:v0.2.0
          command:
            - ./subprovisioner
            - csi-controller-plugin
          env:
            - name: SUBPROVISIONER_IMAGE
              value: *image
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: socket-dir
              mountPath: /run/csi
            - name: dev
              mountPath: /dev
          securityContext:
            privileged: true
        - name: csi-provisioner
          image: registry.k8s.io/sig-storage/csi-provisioner:v3.5.0
          args:
            - --extra-create-metadata  # to get PVC/PV info in CreateVolume()
          volumeMounts:
            - name: socket-dir
              mountPath: /run/csi
        - name: csi-snapshotter
          image: registry.k8s.io/sig-storage/csi-snapshotter:v6.3.3
          args:
            - --extra-create-metadata  # to get VS/VSC info in CreateSnapshot()
          volumeMounts:
            - name: socket-dir
              mountPath: /run/csi
      volumes:
        - name: socket-dir
          emptyDir:
        - name: dev
          hostPath:
            path: /dev
            type: Directory
